Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/MethodLength:
  Enabled: false
