services:
  db:
    image: ip_monitoring_test/postgres_image:latest
    build: ../containers/postgres
    container_name: ip_monitoring_test_postgres
    env_file:
      - ../env/test.env
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: ip_monitoring_test/migrations_image:latest
    build:
      context: ../..
      dockerfile: docker/containers/migrations/Dockerfile
    container_name: ip_monitoring_test_migrations
    env_file:
      - ../env/test.env
    depends_on:
      db:
        condition: service_healthy

  rspec:
    image: ip_monitoring_test/rspec_image:latest
    build:
      context: ../..
      dockerfile: docker/containers/rspec/Dockerfile
    env_file:
      - ../env/test.env
    volumes:
      - ../..:/app
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

volumes:
  postgres_test_data:
